pipeline:
  name: Build go-pipeline-sample
  identifier: Build_pradeep0323_go_pipeline_sample_1705557005313
  projectIdentifier: harness_demo
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1705554342952
        repoName: pradeep0323/go-pipeline-sample
        build: <+input>
